[package]
name = "mizook"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
dotenvy = "0.15.7"
futures-util = "0.3.34"
reqwest = { version = "0.13.5", features = ["json"] }
serde = "1.0.229"
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "process"] }
tokio-tungstenite = { version = "0.30.0", features = ["rustls-tls-native-roots"] }
urlencoding = "2"
